### ISSUE TITLE
Modularize DHIS 2 GIS API

### ISSUE THREAD

**Issue by turban** [dhis2/gis-api#21]
We sould cosider to modularize the DHIS 2 GIS API so we don't load more functionality than needed: https://webpack.github.io/docs/code-splitting.html

The Google Earth API is 115 kB gzipped.

**Comment by janhenrikoverland** [comment]
Seems webpack 2 will take care of it, so maybe not worth the effort? They call it tree shaking: http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Comment by turban** [comment]
Yes, we should let Webpack deal with the module bundling. As I understand, tree shaking allows us the get rid of code _that will never be used_. In our case, we don't know if the user will add a layer form Google Earth Engine, and we should/could only load this part of the GIS API when needed (on demand).

**Comment by janhenrikoverland** [comment]
Ah, yeah that's a slightly different thing. Agreed.
